### ISSUE TITLE
States don't reset positions properly when performing ctrl + Z

### ISSUE THREAD

**Issue by micahwagner** [AutomatonBuilderGUI/AutomatonBuilderGUI#111]
### Recreation Steps

Start by creating a state far away from the origin. Since there isn't a defined origin on screen, just scroll the grid really far in some direction. Next, create another state next to the first state, and add a transition arrow (you don't have to add the arrow or other state, it just makes it easier to see the issue). Next, move the newly created state some small distance, then undo the action with ctrl+z. The state should move all the way back near the origin instead of the previous location it was in.

**Comment by Meorge** [comment]
@micahwagner 
> Do you remember the original rational for setting the lastPos equal to the absolutePosition instead of the normal position, and how it could be effecting the issue?

I don't, unfortunately - the zoom was implemented by someone else. Looking at the code, it appears that the zoom is accomplished by scaling the entire stage. The `absolutePosition` should be unaffected by scale, whereas `position` should be, so it seems to me like using `position` would make more sense. 

You said that adding transitions causes a similar issue - if you apply the same changes to its code (using `position` instead of `absolutePosition`), does that seem to fix it as well? If so, it may well just be a logical error from the original implementation.

**Comment by micahwagner** [comment]
Thanks for the suggestion! I had a similar idea but I couldn't find the function that takes care of it until just now. I switched it to be position and everything seems to work now. I think the rational for the absolute position is that its relative to the world instead of some parent, but we move everything relative to the parent (grid) anyways so we should be using position. Thanks for the help!
