### ISSUE TITLE
When SnapToGrid is enabled, action stack doesn't update when moving a state.

### ISSUE THREAD

**Issue by noahwagner04** [AutomatonBuilderGUI/AutomatonBuilderGUI#112]
Recreation Steps:
- Enable Snap To Grid
- Add a state
- Move the state
- Notice the action stack doesn't update
- ctrl+z will pop the "Add "q0"" action (should be a move action)

**Comment by noahwagner04** [comment]
@Meorge I added a call to StateManager.completeDragStatesOperation in the SnapToGridEnabled branch of the onDragEnd function in NodeWrapper.ts, which seemed to fix the issue. However, I do have a couple questions.
- Why is this.nodeGroup.getLayer()?.batchDraw(); called in this branch, but not the other select branch? I commented this out and nothing seemed different.
- Should I update the action stack even if the node snaps back to its previous position? With my current solution, if I drag a node and it ends up back at its previous cell location, the action stack will add a move action to the stack (but the delta will be 0). Should I fix this in another issue, or this one?

Thanks.

**Comment by Meorge** [comment]
@noahwagner04 

> Why is `this.nodeGroup.getLayer()?.batchDraw();` called in this branch, but not the other select branch? I commented this out and nothing seemed different.

I'm not entirely sure. I believe the snap-to-grid functionality was implemented by one of the previous capstone students, so it may be that they thought it was necessary to add when it wasn't. I'd say it probably makes sense to leave it be for now, since it isn't directly related to the issue you're targeting as far as I can tell.

> Should I update the action stack even if the node snaps back to its previous position? With my current solution, if I drag a node and it ends up back at its previous cell location, the action stack will add a move action to the stack (but the delta will be 0). Should I fix this in another issue, or this one?

That's a good question. I think it makes sense to not push an action to the action stack if the delta is 0, since ultimately no changes were made to the automaton. If you think it will be easy enough to not push the action when it doesn't change the automaton, then go ahead and implement that; otherwise, we can address it in a later PR.
