### ISSUE TITLE
Dragging multiple states results in lag and uneven movement

### ISSUE THREAD

**Issue by Meorge** [AutomatonBuilderGUI/AutomatonBuilderGUI#113]
**To reproduce:**
1. Create at least two states on an empty canvas.
2. Select both states using Shift + Click.
3. Drag one of the states around. They should move at a slower rate, and the one being directly dragged should move more quickly than the others.

**Comment by noahwagner04** [comment]
Hi @Meorge, I just discovered this bug while trying to fix snapToGrid. From my experience, the bug only happens after you shift & drag the grid from its default position. Also, if you try to ctrl+z the moves, the states don't go back to the correct positions. I'm not sure if that issue is directly related to this one though. 

I'll be happy to work on this issue.
