### ISSUE TITLE
Rename "Clear the Automaton" to "New Automaton"

### ISSUE THREAD

**Issue by Meorge** [AutomatonBuilderGUI/AutomatonBuilderGUI#131]
While they are functionally identical, I think renaming the "Clear the Automaton" function to "New Automaton" would fall more in line with other programs' concepts of file editing, and be more familiar to the user as a result.

**Comment by MohitKambli** [comment]
Hello,
Hope you're doing well
I just wanted to know if this is what is expected or no:

![image](https://github.com/user-attachments/assets/d06fa6df-098c-435f-a281-f104d35bba6e)

Do let me know if there is any misunderstanding or incorrect implementation

Thanks and Regards,
Mohit Kambli

**Comment by Meorge** [comment]
@MohitKambli The update to the button title looks good, but I think it'd also be good to change the icon and color to fit more with the idea of creating a new automaton, rather than "trashing" the current automaton as it currently suggests (with the destructive red color and trash can icon).

**Comment by MohitKambli** [comment]
Hello @Meorge,
Hope you're doing well
I made some changes to the code in order to meet your requirements
This is how it looks in light mode:
![image](https://github.com/user-attachments/assets/13806650-5766-49cf-937e-277c90fd1bab)

This is how it looks in dark mode:
![image](https://github.com/user-attachments/assets/e2712798-0ca0-47d5-86d6-8a2bc3fc3451)

I have integrated the `BiFileBlank` react icon here with a `black` bg-color
If at all you think this doesn't quite fit right with the functionality, then do let me know which would look fine from this [link](https://react-icons.github.io/react-icons/icons/bi/)
Sincere apologies if I understood/implemented anything incorrectly

Thanks and Regards,
Mohit Kambli

**Comment by Meorge** [comment]
@MohitKambli I think that looks good for now! At least for me, it conveys the idea of creating a new blank file. At some point in the future we are planning to redesign some of the UI including file management, so if need be we can revisit it at that time.

**Comment by MohitKambli** [comment]
Hello @Meorge,
Sounds good
So will it be fine if I raise a PR for the requirements that I have implemented so far?
Do let me know your thoughts

Thanks and Regards,
Mohit Kambli

**Comment by Meorge** [comment]
@MohitKambli Opening a PR for this would be great, thanks! I'll do a quick code review and some testing before I merge it into the main branch, but I imagine it should go quite smoothly. :)
