### ISSUE TITLE
Any transition besides last transition generated will remain when node is deleted

### ISSUE THREAD

**Issue by Meorge** [AutomatonBuilderGUI/AutomatonBuilderGUI#49]

**Comment by thundershield** [comment]
Found out that the deleteAllSelectedObjects method was incorrectly removing all non-selected transitions and nodes from their lists, instead of removing the selected ones. Inverted the selection criteria, fixing this. Also resolves the issue where the start node wouldn't reset when another node was deleted first.

**Comment by thundershield** [comment]
Found out that the deleteAllSelectedObjects method was incorrectly removing all non-selected transitions and nodes from their lists, instead of removing the selected ones. Inverted the selection criteria, fixing this. Also resolves the issue where the start node wouldn't reset when another node was deleted first.
