### ISSUE TITLE
Export image of automaton

### ISSUE THREAD

**Issue by Meorge** [AutomatonBuilderGUI/AutomatonBuilderGUI#83]
Users should be able to export an image of their automaton, that could be submitted for an assignment for example.

**Comment by nilcinova** [comment]
Hi, I am sorry I was pretty busy, but I have worked on the task. Just figuring out the details and I also want to ask for advice. So what I am pretty much doing in the code is using the data i have about the node and transition wrappers in StateManager, to replicate the diagram and then convert it to an SVG when the user clicks a button. I am sending you the diagram images and button. I am not sure how the button should look, so please leave a comment about that :). I am not done, since i want to still make the transition look more closer to the original. Just wanted some feedback about the stuff that I have done. 
![Screenshot 2024-11-13 075009](https://github.com/user-attachments/assets/af1f182d-73ae-49a1-8145-c2314567ab06)
![Screenshot 2024-11-13 075030](https://github.com/user-attachments/assets/4ae3c815-e50a-4c3e-a421-8affc73fd833)
![Screenshot 2024-11-13 075555](https://github.com/user-attachments/assets/7a6274c6-de29-4d3d-9b24-8ba6220211a3)

**Comment by Meorge** [comment]
No worries, I know life and other responsibilities can get busy. Thanks for working on this - I'm really excited to see it implemented! 😄 

> So what I am pretty much doing in the code is using the data i have about the node and transition wrappers in StateManager, to replicate the diagram and then convert it to an SVG when the user clicks a button.

I wanted to ask here if you'd looked into generating the image data directly from Konva, rather than recreating the diagram as an SVG? Konva's [Canvas class has a method `toDataURL(mimeType, quality)`](https://konvajs.org/api/Konva.Canvas.html#toDataURL__anchor) which sounds like it would be able to export the canvas contents directly. [There is a tutorial on the Konva website for how to use it here.](https://konvajs.org/docs/data_and_serialization/High-Quality-Export.html)

Unless there are other particular reasons to recreate the diagram, I think this would be a more efficient approach. Improvements to the in-app drawing, such as making the loops smoother or improving transition label placement, would also apply to the exported images, instead of the changes having to be implemented on both versions of the diagram drawing.

The one caveat I could see popping up when it comes to doing this is that the user panning and zooming the canvas *might* cause the rendered output image to be different. If this is the case, it might be possible to create a duplicate of the canvas in memory (hidden from the user), scale and translate it to something appropriate, take the image of it, then discard the canvas copy.

> I am not sure how the button should look, so please leave a comment about that :)

Since this would be downloading just an image of the state diagram that couldn't be loaded back into the software, I think a "photo" or "picture" icon might be more fitting. From [Bootstrap Icons](https://icons.getbootstrap.com), where many of the current UI's icons are from, I think [`camera`](https://icons.getbootstrap.com/icons/camera/) or [`image`](https://icons.getbootstrap.com/icons/image/) might work well.

**Comment by nilcinova** [comment]
Thanks for the feedback and tips! :) I did not know about the kanva method, I will try to impement the export that way.

**Comment by nilcinova** [comment]
Hello :) I am pretty sure, that I am done with the task. Please tell me if there are any things that need to be changed. I used the function you told me about to export the diagram. To fight the zooming and the pan, while exporting I temporarily reset the scale and position. Pull request: https://github.com/AutomatonBuilderGUI/AutomatonBuilderGUI/pull/149
